server:
  port: 3000

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      teste: teste
    consumer:
      group-id: order-group
      auto-offset-reset:

  data:
    mongodb:
      database: admin
      uri: ${MONG_DB_URI:mongodb://admin:123456@localhost:27017}